import ClerkWrapper from '../ClerkWrapper';
import ReduxProvider from '../store/ReduxProvider';

import 'bootstrap/dist/css/bootstrap.min.css';
import TopNav from '../_components/TopNav';
import Footer from '../_components/Footer';
import Script from 'next/script';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Script
        src="https://checkout.razorpay.com/v1/checkout.js"
        strategy="afterInteractive"
      />
      <ClerkWrapper>
        <TopNav />
        <ReduxProvider>
          {children}
        </ReduxProvider>
        <Footer />
      </ClerkWrapper>
    </>
  );
}
